# Generated by Django 5.1.1 on 2025-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Famille publique"),
        ),
    ]
